### ISSUE TITLE
Create Navbar for the website

### ISSUE THREAD

**Issue by SuyashSonawane** [devscollab/devscollab.github.io#23]
Create a navbar that consists of 
- about-us
- projects
- join-us

Important points
- navbar should be responsive 
- navbar should match the theme
- on clicking the nav-link, the page should be scrolled to associated content with a smooth animation

**Comment by bhavansh** [comment]
Can you assign this issue to me, I will start working on it 👍🏻

**Comment by TheoGU** [comment]
@bhavansh if you give up, I'd like to work on it 😉

**Comment by ayushkumarsinha** [comment]
Let me know if i can contribute!

**Comment by tejasmorkar** [comment]
@bhavansh I have assigned the other issue to you. 

@TheoGU you can start working on this one.

**Comment by tejasmorkar** [comment]
> Let me know if i can contribute!

You can check out other issues and repos too!

**Comment by tejasmorkar** [comment]
@TheoGU are you working on this issue?

**Comment by TheoGU** [comment]
@tejasmorkar not for the moment

**Comment by tejasmorkar** [comment]
We need this issue resolved soon, so I'll change the assignee.

@bhavansh or @ayushkumarsinha would one of you like to work on this?

**Comment by bhavansh** [comment]
ok I can work on it

**Comment by tejasmorkar** [comment]
@bhavansh you are now assigned to this issue 👍
