### ISSUE TITLE
Enhancing Cards 

### ISSUE THREAD

**Issue by SuyashSonawane** [devscollab/devscollab.github.io#24]
The following changes are needed to be done on the `project-overview`  section of the website 

Todo
- Add the following metrics on the cards using `Github API` (json object is fetched and available at [Line 51](https://github.com/devscollab/devscollab.github.io/blob/5f48230c4666c24c1e0bc50eba9cbf242ce74bab/js/main.js#L51)), 
["forks","open_issues", "watchers"]
- When clicked on the card, it should be opened on a new tab

Important Points
- All changes should be responsive  
- Before creating a PR, send a screenshot in this issue thread

![image](https://user-images.githubusercontent.com/35629339/94911983-9b44a380-04c4-11eb-85f3-c1b529d1ff6f.png)

**Comment by Lukydemboy** [comment]
I can do this, is it possible to assign me to this issue?

**Comment by Lukydemboy** [comment]
![Schermafbeelding 2020-10-02 om 13 49 44](https://user-images.githubusercontent.com/20842527/94920227-308c6b80-04b6-11eb-8207-08dcdc533440.png)

**Comment by tejasmorkar** [comment]
Sure, you can work on it.

**Comment by Lukydemboy** [comment]
![Uploading Schermafbeelding 2020-10-02 om 15.01.07.png…]()

**Comment by tejasmorkar** [comment]
> Uploading Schermafbeelding 2020-10-02 om 15.01.07.png…

The Screenshot is not uploaded properly, could you send it again?

**Comment by Lukydemboy** [comment]
![Schermafbeelding 2020-10-02 om 15 01 07](https://user-images.githubusercontent.com/20842527/94930759-2fb00580-04c7-11eb-9ff1-82fdab1542a5.png)

**Comment by tejasmorkar** [comment]
Great work!

**Comment by Lukydemboy** [comment]
Thanks! Will be done soon.

**Comment by tejasmorkar** [comment]
Thank you for your contribution @Lukydemboy 🎉
