### ISSUE TITLE
Enhancing Member Cards

### ISSUE THREAD

**Issue by SuyashSonawane** [devscollab/devscollab.github.io#25]
The following changes are needed to be done on [this page](https://devscollab.com/pages/members.html)

Todo
- Fetch member information like followers, repo count and render it on the cards keeping the theme in mind

Important Points

- All changes should be responsive
- Before creating a PR, send a screenshot in this issue thread

![image](https://user-images.githubusercontent.com/35629339/94916290-0f367a00-04cc-11eb-960e-45ebfcf46905.png)

**Comment by bhavansh** [comment]
Can you assign this to me 🥺

**Comment by tejasmorkar** [comment]
You can start working on it! 👍

**Comment by bhavansh** [comment]
![image](https://user-images.githubusercontent.com/45139041/95017143-2b294f80-0675-11eb-91dd-a6e1a09d1cef.png)
![image](https://user-images.githubusercontent.com/45139041/95017154-3b412f00-0675-11eb-8af9-2956da48d368.png)

Still needs responsiveness but I think I have added most of the things using from GitHub API.
Open to suggestions color scheme, any more additions, and any other improvement suggestion😄

**Comment by bhavansh** [comment]
[Website](https://bhavansh.github.io/devscollab.github.io/pages/members.html)

You can check it out here

**Comment by SuyashSonawane** [comment]
Great work @bhavansh 🥳

Can we go for light theme on cards as well, because now the background being white and cards in dark theme the contrast is too much.

What we can do, have light cards with a subtle shadow

**Comment by bhavansh** [comment]
ok I will make the changes and create a pull req, latley having problems with laptop so was busy 😅

**Comment by bhavansh** [comment]
I lightened the theme , couldn't think of something better so went for black and white.
Website is on the previous link. I have created a pull req for it
