### ISSUE TITLE
Create a new Page | CODE of CONDUCT

### ISSUE THREAD

**Issue by SuyashSonawane** [devscollab/devscollab.github.io#26]
The following changes are needed to be done on the `footer` section of the website

Todo
- Create a new HTML page with a matching color scheme with the content from [here](https://github.com/devscollab/devscollab.github.io/blob/master/CODE_OF_CONDUCT.md)

Important Points

- All changes should be responsive
- Before creating a PR, send a screenshot in this issue thread

![image](https://user-images.githubusercontent.com/35629339/94916818-fda1a200-04cc-11eb-8ea8-51c731e83512.png)

**Comment by Exter-dg** [comment]
I am working on this

**Comment by tejasmorkar** [comment]
Wait until you are assigned to the Issue, or the PR will be marked as invalid.

**Comment by tejasmorkar** [comment]
You can start working on it @Exter-dg

**Comment by Exter-dg** [comment]
Screenshots for Reference:

![Screenshot from 2020-10-03 15-56-30](https://user-images.githubusercontent.com/46609729/94989362-dcef5000-0591-11eb-804d-8d2492155201.png)

![Screenshot from 2020-10-03 15-56-32](https://user-images.githubusercontent.com/46609729/94989354-ccd77080-0591-11eb-9816-db5fc766750f.png)
![1](https://user-images.githubusercontent.com/46609729/94989358-d1038e00-0591-11eb-98e7-1e805adf1e7c.png)
