### ISSUE TITLE
Fix Navigation

### ISSUE THREAD

**Issue by SuyashSonawane** [devscollab/devscollab.github.io#27]
The following changes are needed to be done on the `main` and `members` page of the website

Todo
- Make the footer links for members and home open in the same tab

Important Points

- All changes should be responsive
- Before creating a PR, send a screenshot in this issue thread

![image](https://user-images.githubusercontent.com/35629339/94917207-c089df80-04cd-11eb-8d30-0125e47e5baa.png)
![image](https://user-images.githubusercontent.com/35629339/94917368-09da2f00-04ce-11eb-967a-7fb3e8dba423.png)

**Comment by hexifox** [comment]
Hi, 

I am looking for first issues and am interested in taking a few on your repo.
However, after following your contributing guide without issues, it seems that the repo is missing a .git file.

As a beginner to contributing, is this the normal behaviour ? Shall I use git init or would that cause any issues when submitting a PR?

Sorry if it is a silly question.

**Comment by tejasmorkar** [comment]
> Hi,
> 
> I am looking for first issues and am interested in taking a few on your repo.
> However, after following your contributing guide without issues, it seems that the repo is missing a .git file.
> 
> As a beginner to contributing, is this the normal behaviour ? Shall I use git init or would that cause any issues when submitting a PR?
> 
> Sorry if it is a silly question.

When you fork a repo and clone it to your system, the .git file is added. All you need to do is follow the steps provided in the CONTRIBUTING.md file. 

If you are completely new to GitHub we can help you make good and meaningful PRs if you join us in the event tomorrow. 
Find all the details over here: https://bit.ly/hacktoberfest-pccoeacm

**Comment by dimlaksana** [comment]
Can I work on this?

**Comment by tejasmorkar** [comment]
Sure you can!

**Comment by dimlaksana** [comment]
So when I was working on  #39 I noticed color inconsistency on footer font between main and members page.
Is that on purpose? if not I'll be happy to make PR to match them up!

**Comment by tejasmorkar** [comment]
@dimlaksana, it would be great if you could open an issue for that and wait until assigned. This way, it becomes easier for us to keep a track of it. We'll assign it to you as soon as possible. 😄
