### ISSUE TITLE
Create a new Page | License 

### ISSUE THREAD

**Issue by SuyashSonawane** [devscollab/devscollab.github.io#29]
The following changes are needed to be done on the footer section of the website

Todo

- Create a new HTML page with a matching color scheme with the content from [here](https://raw.githubusercontent.com/devscollab/devscollab.github.io/master/LICENSE)

Important Points
- All changes should be responsive
- Before creating a PR, send a screenshot in this issue thread

![image](https://user-images.githubusercontent.com/35629339/94918599-853ce000-04d0-11eb-8396-d7bfdbf195fe.png)

**Comment by niftyrinki** [comment]
Working on it

**Comment by niftyrinki** [comment]
Screenshots for reference:
<img width="1277" alt="Screenshot 2020-10-02 at 5 36 14 PM" src="https://user-images.githubusercontent.com/17089244/94921470-021e8880-04d6-11eb-8ff1-7a21742eb1ad.png">
<img width="492" alt="Screenshot 2020-10-02 at 5 36 26 PM" src="https://user-images.githubusercontent.com/17089244/94921480-06e33c80-04d6-11eb-97ea-575701d7ada2.png">

**Comment by tejasmorkar** [comment]
Looks great 👍 

For further contributions, please wait until you are assigned before you start working on any issue.
