### ISSUE TITLE
Update Discord Invite Link 

### ISSUE THREAD

**Issue by SuyashSonawane** [devscollab/devscollab.github.io#31]
The following changes are needed to be done at 2 sections of the website

Todo
Update the discord invite link to https://discord.gg/THA7ZKJ

![image](https://user-images.githubusercontent.com/35629339/94919539-427c0780-04d2-11eb-9636-ba2d78e857af.png)
![image](https://user-images.githubusercontent.com/35629339/94919557-4ad44280-04d2-11eb-90b3-0980af593c2c.png)

**Comment by brunoromeiro** [comment]
Hello can I help you with this issue?

**Comment by zikos2** [comment]
Can i work on this issue?

**Comment by tejasmorkar** [comment]
@brunoromeiro you can reopen the PR for now. 

We had to mark it invalid due to the heavy inflow of PRs this month, do follow the guidelines for further contributions😃 

Thank you for your contribution!
