### ISSUE TITLE
There is a white space between the contact-us and the navigation bar!

### ISSUE THREAD

**Issue by kdarshan425** [devscollab/devscollab.github.io#43]
![dci](https://user-images.githubusercontent.com/64018424/94994184-b93d0180-05b3-11eb-8631-5adf2e989bad.PNG)
Here you can see there is white space between the contact-us and the navigation bar. Can I work on this issue? it might be helpful for this project, In the morning I'd directly send the pull request , I apologies for that !

**Comment by tejasmorkar** [comment]
Okay I'll assign you to this issue
