### ISSUE TITLE
Unmatching font color on footer section

### ISSUE THREAD

**Issue by dimlaksana** [devscollab/devscollab.github.io#46]
Hi @tejasmorkar, 
So when I was working on #39, I found unmatching font color between `main` and `members` page on the footer section. 

![20201004_013322](https://user-images.githubusercontent.com/57056689/94997715-e86d6600-05e7-11eb-9db6-f2ea5bc81354.jpg)
![20201004_013156](https://user-images.githubusercontent.com/57056689/94997728-f6bb8200-05e7-11eb-8f89-07514c926354.jpg)

Assign me this issue, I'll fix it.

**Comment by tejasmorkar** [comment]
Okay 👍
