### ISSUE TITLE
SEO for the website

### ISSUE THREAD

**Issue by tejasmorkar** [devscollab/devscollab.github.io#52]
The description needs to be better in using SEO tags and appropriate images from the website should appear while sharing it on social media. Suggest any other changes or additions that can be done for improving the website SEO.

**Comment by IsautierEloise** [comment]
Hello, could you assign this to me please ?

**Comment by tejasmorkar** [comment]
Yeah sure!

**Comment by IsautierEloise** [comment]
https://github.com/devscollab/devscollab.github.io/pull/53
